######################################################################
# Automatically generated by qmake (3.0) mer. oct. 14 11:02:03 2015
######################################################################

TEMPLATE = app
TARGET = 3DAssemblies
INCLUDEPATH += . \
               src \
               src/Qt \
               src/Irrlicht \
               src/SpaceNavigator \
               src/cartouches_stacks \
               src/Polhemus

# Input
HEADERS += ui_ConfigurationWindowBase.h \
           ui_ManipulationWindowBase.h \
           ui_SelectionWindowBase.h \
           src/colormod.hpp \
           src/Controller.hpp \
           src/Coordinates.hpp \
           src/Experiments.hpp \
           src/MediaList.hpp \
           src/Node.hpp \
           src/cartouches_stacks/AssemblyWindow.h \
           src/cartouches_stacks/CameraArea.h \
           src/cartouches_stacks/Cartouche.h \
           src/cartouches_stacks/ConfigurationWindow.h \
           src/cartouches_stacks/TargetManager.h \
           src/cartouches_stacks/v4l2grab.h \
           src/Irrlicht/AxesSceneNode.hpp \
           src/Irrlicht/IrrlichtController.hpp \
           src/Irrlicht/maximum.hpp \
           src/Irrlicht/QIrrlichtWidget.hpp \
           src/Irrlicht/utils.hpp \
           src/Irrlicht/stereo.hpp \
           src/Polhemus/PiTracker.hpp \
           src/Polhemus/PolhemusReader.hpp \
           src/Qt/ConfigurationWindow.hpp \
           src/Qt/ManipulationWindow.hpp \
           src/Qt/MPushButton.hpp \
           src/Qt/SelectionWindow.hpp \
           src/SpaceNavigator/SpaceNavigatorServer.hpp \
           src/SpaceNavigator/spnav_events.h \
           moc_QIrrlichtWidget.cpp
FORMS += ui/ConfigurationWindowBase.ui \
         ui/ManipulationWindowBase.ui \
         ui/SelectionWindowBase.ui
SOURCES += src/colormod.cpp \
           src/Controller.cpp \
           src/Coordinates.cpp \
           src/main.cpp \
           src/MediaList.cpp \
           src/cartouches_stacks/AssemblyWindow.cpp \
           src/cartouches_stacks/CameraArea.cpp \
           src/cartouches_stacks/Cartouche.cpp \
           src/cartouches_stacks/ConfigurationWindow.cpp \
           src/cartouches_stacks/main.cpp \
           src/cartouches_stacks/TargetManager.cpp \
           src/cartouches_stacks/v4l2grab.c \
           src/Irrlicht/AxesSceneNode.cpp \
           src/Irrlicht/IrrlichtController.cpp \
           src/Irrlicht/QIrrlichtWidget.cpp \
           src/Irrlicht/utils.cpp \
           src/Irrlicht/stereo.cpp \
           src/Polhemus/PiTracker.cpp \
           src/Polhemus/PolhemusReader.cpp \
           src/Qt/ConfigurationWindow.cpp \
           src/Qt/ManipulationWindow.cpp \
           src/Qt/SelectionWindow.cpp \
           src/SpaceNavigator/client.c \
           src/SpaceNavigator/server.c \
           src/SpaceNavigator/server_thread.c \
           src/SpaceNavigator/SpaceNavigatorServer.cpp

INCLUDEPATH += /usr/local/include/irrlicht-1.9/
LIBS += -L/usr/local/lib/ -lIrrlicht-1.9 -lXrandr -lXi -lXxf86vm
LIBS += -lspnav -lX11 -lpthread -lusb-1.0
SOURCES -= src/SpaceNavigator/client.c
SOURCES -= src/SpaceNavigator/server.c
SOURCES -= src/SpaceNavigator/server_thread.c
SOURCES -= src/cartouches_stacks/AssemblyWindow.cpp
SOURCES -= src/cartouches_stacks/CameraArea.cpp
SOURCES -= src/cartouches_stacks/Cartouche.cpp
SOURCES -= src/cartouches_stacks/ConfigurationWindow.cpp
SOURCES -= src/cartouches_stacks/main.cpp
SOURCES -= src/cartouches_stacks/TargetManager.cpp
SOURCES -= src/cartouches_stacks/v4l2grab.c
HEADERS -= src/cartouches_stacks/AssemblyWindow.h
HEADERS -= src/cartouches_stacks/CameraArea.h
HEADERS -= src/cartouches_stacks/Cartouche.h
HEADERS -= src/cartouches_stacks/ConfigurationWindow.h
HEADERS -= src/cartouches_stacks/TargetManager.h
HEADERS -= src/cartouches_stacks/v4l2grab.h
QT += widgets core gui
