#############################################################################
# Makefile for building: Assemblies
# Generated by qmake (3.0) (Qt 5.3.2)
# Project:  Assemblies.pro
# Template: app
# Command: /usr/lib/x86_64-linux-gnu/qt5/bin/qmake -o Makefile Assemblies.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -m64 -pipe -O2 -Wall -W -D_REENTRANT -fPIE $(DEFINES)
CXXFLAGS      = -m64 -pipe -O2 -Wall -W -D_REENTRANT -fPIE $(DEFINES)
INCPATH       = -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I. -I. -Isrc -Isrc/Qt -Isrc/Irrlicht -Isrc/SpaceNavigator -Isrc/cartouches_stacks -Isrc/Polhemus -isystem /usr/local/include/irrlicht-1.9 -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I.
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS) -L/usr/X11R6/lib64 -L/usr/local/lib/ -lIrrlicht-1.9 -lXrandr -lXi -lXxf86vm -lspnav -lX11 -lusb-1.0 -lQt5Widgets -lQt5Gui -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/lib/x86_64-linux-gnu/qt5/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = src/colormod.cpp \
		src/Controller.cpp \
		src/Coordinates.cpp \
		src/main.cpp \
		src/MediaList.cpp \
		src/Irrlicht/AxesSceneNode.cpp \
		src/Irrlicht/IrrlichtController.cpp \
		src/Irrlicht/QIrrlichtWidget.cpp \
		src/Irrlicht/utils.cpp \
		src/Irrlicht/stereo.cpp \
		src/Polhemus/PiTracker.cpp \
		src/Polhemus/PolhemusReader.cpp \
		src/Qt/ConfigurationWindow.cpp \
		src/Qt/ManipulationWindow.cpp \
		src/Qt/SelectionWindow.cpp \
		src/SpaceNavigator/SpaceNavigatorServer.cpp moc_ConfigurationWindow.cpp \
		moc_ManipulationWindow.cpp \
		moc_SelectionWindow.cpp
OBJECTS       = colormod.o \
		Controller.o \
		Coordinates.o \
		main.o \
		MediaList.o \
		AxesSceneNode.o \
		IrrlichtController.o \
		QIrrlichtWidget.o \
		utils.o \
		stereo.o \
		PiTracker.o \
		PolhemusReader.o \
		ConfigurationWindow.o \
		ManipulationWindow.o \
		SelectionWindow.o \
		SpaceNavigatorServer.o \
		moc_ConfigurationWindow.o \
		moc_ManipulationWindow.o \
		moc_SelectionWindow.o
DIST          = /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/shell-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_x11extras.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		Assemblies.pro src/colormod.cpp \
		src/Controller.cpp \
		src/Coordinates.cpp \
		src/main.cpp \
		src/MediaList.cpp \
		src/Irrlicht/AxesSceneNode.cpp \
		src/Irrlicht/IrrlichtController.cpp \
		src/Irrlicht/QIrrlichtWidget.cpp \
		src/Irrlicht/utils.cpp \
		src/Irrlicht/stereo.cpp \
		src/Polhemus/PiTracker.cpp \
		src/Polhemus/PolhemusReader.cpp \
		src/Qt/ConfigurationWindow.cpp \
		src/Qt/ManipulationWindow.cpp \
		src/Qt/SelectionWindow.cpp \
		src/SpaceNavigator/SpaceNavigatorServer.cpp
QMAKE_TARGET  = Assemblies
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = Assemblies


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)
	mv $(TARGET) ./bin/

$(TARGET): ui_ConfigurationWindowBase.h ui_ManipulationWindowBase.h ui_SelectionWindowBase.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Assemblies.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/shell-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_x11extras.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		Assemblies.pro \
		/usr/lib/x86_64-linux-gnu/libQt5Widgets.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Gui.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Core.prl
	$(QMAKE) -o Makefile Assemblies.pro
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/shell-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_x11extras.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
Assemblies.pro:
/usr/lib/x86_64-linux-gnu/libQt5Widgets.prl:
/usr/lib/x86_64-linux-gnu/libQt5Gui.prl:
/usr/lib/x86_64-linux-gnu/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile Assemblies.pro

qmake_all: FORCE

dist: 
	@test -d .tmp/Assemblies1.0.0 || mkdir -p .tmp/Assemblies1.0.0
	$(COPY_FILE) --parents $(DIST) .tmp/Assemblies1.0.0/ && $(COPY_FILE) --parents ui_ConfigurationWindowBase.h ui_ManipulationWindowBase.h ui_SelectionWindowBase.h src/colormod.hpp src/Controller.hpp src/Coordinates.hpp src/Experiments.hpp src/MediaList.hpp src/Node.hpp src/Irrlicht/AxesSceneNode.hpp src/Irrlicht/IrrlichtController.hpp src/Irrlicht/maximum.hpp src/Irrlicht/QIrrlichtWidget.hpp src/Irrlicht/utils.hpp src/Irrlicht/stereo.hpp src/Polhemus/PiTracker.hpp src/Polhemus/PolhemusReader.hpp src/Qt/ConfigurationWindow.hpp src/Qt/ManipulationWindow.hpp src/Qt/MPushButton.hpp src/Qt/SelectionWindow.hpp src/SpaceNavigator/SpaceNavigatorServer.hpp src/SpaceNavigator/spnav_events.h moc_QIrrlichtWidget.cpp .tmp/Assemblies1.0.0/ && $(COPY_FILE) --parents src/colormod.cpp src/Controller.cpp src/Coordinates.cpp src/main.cpp src/MediaList.cpp src/Irrlicht/AxesSceneNode.cpp src/Irrlicht/IrrlichtController.cpp src/Irrlicht/QIrrlichtWidget.cpp src/Irrlicht/utils.cpp src/Irrlicht/stereo.cpp src/Polhemus/PiTracker.cpp src/Polhemus/PolhemusReader.cpp src/Qt/ConfigurationWindow.cpp src/Qt/ManipulationWindow.cpp src/Qt/SelectionWindow.cpp src/SpaceNavigator/SpaceNavigatorServer.cpp .tmp/Assemblies1.0.0/ && $(COPY_FILE) --parents ui/ConfigurationWindowBase.ui ui/ManipulationWindowBase.ui ui/SelectionWindowBase.ui .tmp/Assemblies1.0.0/ && (cd `dirname .tmp/Assemblies1.0.0` && $(TAR) Assemblies1.0.0.tar Assemblies1.0.0 && $(COMPRESS) Assemblies1.0.0.tar) && $(MOVE) `dirname .tmp/Assemblies1.0.0`/Assemblies1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/Assemblies1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all: moc_QIrrlichtWidget.cpp moc_ConfigurationWindow.cpp moc_ManipulationWindow.cpp moc_SelectionWindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_QIrrlichtWidget.cpp moc_ConfigurationWindow.cpp moc_ManipulationWindow.cpp moc_SelectionWindow.cpp
moc_QIrrlichtWidget.cpp: src/Irrlicht/QIrrlichtWidget.hpp
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/guillaume/Dev/Assemblies/Assemblies -I/home/guillaume/Dev/Assemblies/Assemblies -I/home/guillaume/Dev/Assemblies/Assemblies/src -I/home/guillaume/Dev/Assemblies/Assemblies/src/Qt -I/home/guillaume/Dev/Assemblies/Assemblies/src/Irrlicht -I/home/guillaume/Dev/Assemblies/Assemblies/src/SpaceNavigator -I/home/guillaume/Dev/Assemblies/Assemblies/src/cartouches_stacks -I/home/guillaume/Dev/Assemblies/Assemblies/src/Polhemus -I/usr/local/include/irrlicht-1.9 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/4.9 -I/usr/include/x86_64-linux-gnu/c++/4.9 -I/usr/include/c++/4.9/backward -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include src/Irrlicht/QIrrlichtWidget.hpp -o moc_QIrrlichtWidget.cpp

moc_ConfigurationWindow.cpp: ui_ConfigurationWindowBase.h \
		src/Coordinates.hpp \
		src/Irrlicht/IrrlichtController.hpp \
		src/Irrlicht/QIrrlichtWidget.hpp \
		src/Qt/ConfigurationWindow.hpp
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/guillaume/Dev/Assemblies/Assemblies -I/home/guillaume/Dev/Assemblies/Assemblies -I/home/guillaume/Dev/Assemblies/Assemblies/src -I/home/guillaume/Dev/Assemblies/Assemblies/src/Qt -I/home/guillaume/Dev/Assemblies/Assemblies/src/Irrlicht -I/home/guillaume/Dev/Assemblies/Assemblies/src/SpaceNavigator -I/home/guillaume/Dev/Assemblies/Assemblies/src/cartouches_stacks -I/home/guillaume/Dev/Assemblies/Assemblies/src/Polhemus -I/usr/local/include/irrlicht-1.9 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/4.9 -I/usr/include/x86_64-linux-gnu/c++/4.9 -I/usr/include/c++/4.9/backward -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include src/Qt/ConfigurationWindow.hpp -o moc_ConfigurationWindow.cpp

moc_ManipulationWindow.cpp: src/Irrlicht/QIrrlichtWidget.hpp \
		src/Irrlicht/IrrlichtController.hpp \
		src/Coordinates.hpp \
		src/SpaceNavigator/SpaceNavigatorServer.hpp \
		src/SpaceNavigator/spnav_events.h \
		ui_ManipulationWindowBase.h \
		src/Qt/ManipulationWindow.hpp
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/guillaume/Dev/Assemblies/Assemblies -I/home/guillaume/Dev/Assemblies/Assemblies -I/home/guillaume/Dev/Assemblies/Assemblies/src -I/home/guillaume/Dev/Assemblies/Assemblies/src/Qt -I/home/guillaume/Dev/Assemblies/Assemblies/src/Irrlicht -I/home/guillaume/Dev/Assemblies/Assemblies/src/SpaceNavigator -I/home/guillaume/Dev/Assemblies/Assemblies/src/cartouches_stacks -I/home/guillaume/Dev/Assemblies/Assemblies/src/Polhemus -I/usr/local/include/irrlicht-1.9 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/4.9 -I/usr/include/x86_64-linux-gnu/c++/4.9 -I/usr/include/c++/4.9/backward -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include src/Qt/ManipulationWindow.hpp -o moc_ManipulationWindow.cpp

moc_SelectionWindow.cpp: src/MediaList.hpp \
		ui_SelectionWindowBase.h \
		src/Qt/SelectionWindow.hpp
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/guillaume/Dev/Assemblies/Assemblies -I/home/guillaume/Dev/Assemblies/Assemblies -I/home/guillaume/Dev/Assemblies/Assemblies/src -I/home/guillaume/Dev/Assemblies/Assemblies/src/Qt -I/home/guillaume/Dev/Assemblies/Assemblies/src/Irrlicht -I/home/guillaume/Dev/Assemblies/Assemblies/src/SpaceNavigator -I/home/guillaume/Dev/Assemblies/Assemblies/src/cartouches_stacks -I/home/guillaume/Dev/Assemblies/Assemblies/src/Polhemus -I/usr/local/include/irrlicht-1.9 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/4.9 -I/usr/include/x86_64-linux-gnu/c++/4.9 -I/usr/include/c++/4.9/backward -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include src/Qt/SelectionWindow.hpp -o moc_SelectionWindow.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_ConfigurationWindowBase.h ui_ManipulationWindowBase.h ui_SelectionWindowBase.h
compiler_uic_clean:
	-$(DEL_FILE) ui_ConfigurationWindowBase.h ui_ManipulationWindowBase.h ui_SelectionWindowBase.h
ui_ConfigurationWindowBase.h: ui/ConfigurationWindowBase.ui
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic ui/ConfigurationWindowBase.ui -o ui_ConfigurationWindowBase.h

ui_ManipulationWindowBase.h: ui/ManipulationWindowBase.ui
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic ui/ManipulationWindowBase.ui -o ui_ManipulationWindowBase.h

ui_SelectionWindowBase.h: ui/SelectionWindowBase.ui
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic ui/SelectionWindowBase.ui -o ui_SelectionWindowBase.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

colormod.o: src/colormod.cpp src/colormod.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o colormod.o src/colormod.cpp

Controller.o: src/Controller.cpp src/Controller.hpp \
		src/MediaList.hpp \
		src/Qt/ManipulationWindow.hpp \
		src/Irrlicht/QIrrlichtWidget.hpp \
		src/Irrlicht/IrrlichtController.hpp \
		src/Coordinates.hpp \
		src/SpaceNavigator/SpaceNavigatorServer.hpp \
		src/SpaceNavigator/spnav_events.h \
		ui_ManipulationWindowBase.h \
		src/Qt/SelectionWindow.hpp \
		ui_SelectionWindowBase.h \
		src/Qt/ConfigurationWindow.hpp \
		ui_ConfigurationWindowBase.h \
		src/Polhemus/PolhemusReader.hpp \
		src/Polhemus/PiTracker.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Controller.o src/Controller.cpp

Coordinates.o: src/Coordinates.cpp src/Coordinates.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Coordinates.o src/Coordinates.cpp

main.o: src/main.cpp src/SpaceNavigator/SpaceNavigatorServer.hpp \
		src/Coordinates.hpp \
		src/SpaceNavigator/spnav_events.h \
		src/Controller.hpp \
		src/MediaList.hpp \
		src/Qt/ManipulationWindow.hpp \
		src/Irrlicht/QIrrlichtWidget.hpp \
		src/Irrlicht/IrrlichtController.hpp \
		ui_ManipulationWindowBase.h \
		src/Qt/SelectionWindow.hpp \
		ui_SelectionWindowBase.h \
		src/Qt/ConfigurationWindow.hpp \
		ui_ConfigurationWindowBase.h \
		src/Polhemus/PolhemusReader.hpp \
		src/Polhemus/PiTracker.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o src/main.cpp

MediaList.o: src/MediaList.cpp src/MediaList.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MediaList.o src/MediaList.cpp

AxesSceneNode.o: src/Irrlicht/AxesSceneNode.cpp src/Irrlicht/AxesSceneNode.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o AxesSceneNode.o src/Irrlicht/AxesSceneNode.cpp

IrrlichtController.o: src/Irrlicht/IrrlichtController.cpp src/Irrlicht/IrrlichtController.hpp \
		src/Irrlicht/QIrrlichtWidget.hpp \
		src/Coordinates.hpp \
		src/Irrlicht/AxesSceneNode.hpp \
		src/Qt/ConfigurationWindow.hpp \
		ui_ConfigurationWindowBase.h \
		src/colormod.hpp \
		src/Irrlicht/maximum.hpp \
		src/Irrlicht/utils.hpp \
		src/Irrlicht/stereo.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o IrrlichtController.o src/Irrlicht/IrrlichtController.cpp

QIrrlichtWidget.o: src/Irrlicht/QIrrlichtWidget.cpp src/Irrlicht/QIrrlichtWidget.hpp \
		src/Irrlicht/stereo.hpp \
		moc_QIrrlichtWidget.cpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o QIrrlichtWidget.o src/Irrlicht/QIrrlichtWidget.cpp

utils.o: src/Irrlicht/utils.cpp src/Irrlicht/utils.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o utils.o src/Irrlicht/utils.cpp

stereo.o: src/Irrlicht/stereo.cpp src/Irrlicht/stereo.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o stereo.o src/Irrlicht/stereo.cpp

PiTracker.o: src/Polhemus/PiTracker.cpp src/Polhemus/PiTracker.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o PiTracker.o src/Polhemus/PiTracker.cpp

PolhemusReader.o: src/Polhemus/PolhemusReader.cpp src/Polhemus/PolhemusReader.hpp \
		src/Coordinates.hpp \
		src/Polhemus/PiTracker.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o PolhemusReader.o src/Polhemus/PolhemusReader.cpp

ConfigurationWindow.o: src/Qt/ConfigurationWindow.cpp src/Qt/ConfigurationWindow.hpp \
		ui_ConfigurationWindowBase.h \
		src/Coordinates.hpp \
		src/Irrlicht/IrrlichtController.hpp \
		src/Irrlicht/QIrrlichtWidget.hpp \
		src/Controller.hpp \
		src/MediaList.hpp \
		src/Qt/ManipulationWindow.hpp \
		src/SpaceNavigator/SpaceNavigatorServer.hpp \
		src/SpaceNavigator/spnav_events.h \
		ui_ManipulationWindowBase.h \
		src/Qt/SelectionWindow.hpp \
		ui_SelectionWindowBase.h \
		src/Polhemus/PolhemusReader.hpp \
		src/Polhemus/PiTracker.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ConfigurationWindow.o src/Qt/ConfigurationWindow.cpp

ManipulationWindow.o: src/Qt/ManipulationWindow.cpp src/Qt/ManipulationWindow.hpp \
		src/Irrlicht/QIrrlichtWidget.hpp \
		src/Irrlicht/IrrlichtController.hpp \
		src/Coordinates.hpp \
		src/SpaceNavigator/SpaceNavigatorServer.hpp \
		src/SpaceNavigator/spnav_events.h \
		ui_ManipulationWindowBase.h \
		src/Controller.hpp \
		src/MediaList.hpp \
		src/Qt/SelectionWindow.hpp \
		ui_SelectionWindowBase.h \
		src/Qt/ConfigurationWindow.hpp \
		ui_ConfigurationWindowBase.h \
		src/Polhemus/PolhemusReader.hpp \
		src/Polhemus/PiTracker.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ManipulationWindow.o src/Qt/ManipulationWindow.cpp

SelectionWindow.o: src/Qt/SelectionWindow.cpp src/Qt/SelectionWindow.hpp \
		src/MediaList.hpp \
		ui_SelectionWindowBase.h \
		src/Controller.hpp \
		src/Qt/ManipulationWindow.hpp \
		src/Irrlicht/QIrrlichtWidget.hpp \
		src/Irrlicht/IrrlichtController.hpp \
		src/Coordinates.hpp \
		src/SpaceNavigator/SpaceNavigatorServer.hpp \
		src/SpaceNavigator/spnav_events.h \
		ui_ManipulationWindowBase.h \
		src/Qt/ConfigurationWindow.hpp \
		ui_ConfigurationWindowBase.h \
		src/Polhemus/PolhemusReader.hpp \
		src/Polhemus/PiTracker.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o SelectionWindow.o src/Qt/SelectionWindow.cpp

SpaceNavigatorServer.o: src/SpaceNavigator/SpaceNavigatorServer.cpp src/colormod.hpp \
		src/SpaceNavigator/SpaceNavigatorServer.hpp \
		src/Coordinates.hpp \
		src/SpaceNavigator/spnav_events.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o SpaceNavigatorServer.o src/SpaceNavigator/SpaceNavigatorServer.cpp

moc_ConfigurationWindow.o: moc_ConfigurationWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ConfigurationWindow.o moc_ConfigurationWindow.cpp

moc_ManipulationWindow.o: moc_ManipulationWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ManipulationWindow.o moc_ManipulationWindow.cpp

moc_SelectionWindow.o: moc_SelectionWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_SelectionWindow.o moc_SelectionWindow.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

