######################################################################
# Automatically generated by qmake (3.0) dim. juil. 5 22:00:28 2015
######################################################################

TEMPLATE = app
TARGET = cartouches_stacks
INCLUDEPATH += .

# Input
HEADERS += AssemblyWindow.h \
           CameraArea.h \
           Cartouche.h \
           ConfigurationWindow.h \
           TargetManager.h \
           v4l2grab.h
SOURCES += AssemblyWindow.cpp \
           CameraArea.cpp \
           Cartouche.cpp \
           ConfigurationWindow.cpp \
           main.cpp \
           TargetManager.cpp \
           v4l2grab.c

QT += widgets

